import React, { useState } from "react";
import { Button, Toast } from "react-bootstrap";

function ToastsEx() {
  const [show, setShow] = useState(false);

  const toggleShow = () => setShow(!show);

  return (
    <div>
      <Button onClick={toggleShow}>Click here to see what happen</Button>
      <Toast show={show} onClose={toggleShow}>
        <Toast.Header>
          <strong className="mr-auto">Bootstrap</strong>
          <small>11 mins ago</small>
        </Toast.Header>
        <Toast.Body>Hello, world! This is a toast message generated by using ChatGPT.</Toast.Body>
      </Toast>
    </div>
  );
}

export default ToastsEx;
